force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DL-{00000000}</displayFormat>
        <label>Debug Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DebugLog.cls
public with sharing class DebugLog {

    public static List<String> logRows = new List<String>();

    public static String between = '\n\n';

    public static void add(String logEntry) {
        logRows.add(logEntry);
    }

    public static String getLog() {
        return String.join(logRows, between);
    }

    public static void saveLog() {
        if(logRows != null & !logRows.isEmpty()) {
            insert new Debug_Log__c(Log__c = getLog());
        }
    }
}